[package]
name = "homebot"
version = "0.0.1"
edition = "2018"

[build-dependencies]
bindgen = { version = "0.59", optional = true }

[dependencies]
serde_yaml = "0.8.7"
serde = "*"


[features]

sim = ["dep:bindgen"]
live = []
