[package]
name = "homebot"
version = "0.0.1"
edition = "2018"

[dependencies]
tokio-serial = "5.4.5"
gpio-cdev = "0.5.1"
tokio = { version = "1", features = ["full"] }
regex = "1.10.2"        # Port detection

[features]
sim = []
test = []
live = []
